# Generated by Django 4.2.2 on 2023-06-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_pic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic_img',
            field=models.CharField(max_length=500, verbose_name='Изображение товара'),
        ),
    ]
