# Generated by Django 4.2.2 on 2023-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_pic_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.IntegerField(default=1, verbose_name='Остаток товара на складе'),
        ),
    ]
