# Generated by Django 4.2.2 on 2023-06-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='balance',
            field=models.PositiveIntegerField(default=1, verbose_name='Остаток товара на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование продукта'),
        ),
    ]
